/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Po3aorderCreateInput } from "./Po3aorderCreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreatePo3aorderArgs {
  @ApiProperty({
    required: true,
    type: () => Po3aorderCreateInput,
  })
  @ValidateNested()
  @Type(() => Po3aorderCreateInput)
  @Field(() => Po3aorderCreateInput, { nullable: false })
  data!: Po3aorderCreateInput;
}

export { CreatePo3aorderArgs as CreatePo3aorderArgs };
