/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Po3aorderWhereInput } from "./Po3aorderWhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Po3aorderOrderByInput } from "./Po3aorderOrderByInput";

@ArgsType()
class Po3aorderFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Po3aorderWhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Po3aorderWhereInput, { nullable: true })
  @Type(() => Po3aorderWhereInput)
  where?: Po3aorderWhereInput;

  @ApiProperty({
    required: false,
    type: [Po3aorderOrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Po3aorderOrderByInput], { nullable: true })
  @Type(() => Po3aorderOrderByInput)
  orderBy?: Array<Po3aorderOrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Po3aorderFindManyArgs as Po3aorderFindManyArgs };
