/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { OfStoreService } from "../ofStore.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { OfStoreCreateInput } from "./OfStoreCreateInput";
import { OfStoreWhereInput } from "./OfStoreWhereInput";
import { OfStoreWhereUniqueInput } from "./OfStoreWhereUniqueInput";
import { OfStoreFindManyArgs } from "./OfStoreFindManyArgs";
import { OfStoreUpdateInput } from "./OfStoreUpdateInput";
import { OfStore } from "./OfStore";
import { Po3aorderFindManyArgs } from "../../po3aorder/base/Po3aorderFindManyArgs";
import { Po3aorder } from "../../po3aorder/base/Po3aorder";
import { Po3aorderWhereUniqueInput } from "../../po3aorder/base/Po3aorderWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class OfStoreControllerBase {
  constructor(
    protected readonly service: OfStoreService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: OfStore })
  @nestAccessControl.UseRoles({
    resource: "OfStore",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: OfStoreCreateInput): Promise<OfStore> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        fld1: true,
        fld2: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [OfStore] })
  @ApiNestedQuery(OfStoreFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "OfStore",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<OfStore[]> {
    const args = plainToClass(OfStoreFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        fld1: true,
        fld2: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: OfStore })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OfStore",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: OfStoreWhereUniqueInput
  ): Promise<OfStore | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        fld1: true,
        fld2: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: OfStore })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OfStore",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: OfStoreWhereUniqueInput,
    @common.Body() data: OfStoreUpdateInput
  ): Promise<OfStore | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          fld1: true,
          fld2: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: OfStore })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OfStore",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: OfStoreWhereUniqueInput
  ): Promise<OfStore | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          fld1: true,
          fld2: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/po3aorders")
  @ApiNestedQuery(Po3aorderFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Po3aorder",
    action: "read",
    possession: "any",
  })
  async findManyPo3aorders(
    @common.Req() request: Request,
    @common.Param() params: OfStoreWhereUniqueInput
  ): Promise<Po3aorder[]> {
    const query = plainToClass(Po3aorderFindManyArgs, request.query);
    const results = await this.service.findPo3aorders(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        of_store: {
          select: {
            id: true,
          },
        },

        t1: true,
        t2: true,
        t3: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/po3aorders")
  @nestAccessControl.UseRoles({
    resource: "OfStore",
    action: "update",
    possession: "any",
  })
  async connectPo3aorders(
    @common.Param() params: OfStoreWhereUniqueInput,
    @common.Body() body: Po3aorderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      po3aorders: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/po3aorders")
  @nestAccessControl.UseRoles({
    resource: "OfStore",
    action: "update",
    possession: "any",
  })
  async updatePo3aorders(
    @common.Param() params: OfStoreWhereUniqueInput,
    @common.Body() body: Po3aorderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      po3aorders: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/po3aorders")
  @nestAccessControl.UseRoles({
    resource: "OfStore",
    action: "update",
    possession: "any",
  })
  async disconnectPo3aorders(
    @common.Param() params: OfStoreWhereUniqueInput,
    @common.Body() body: Po3aorderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      po3aorders: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
