/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { Po3aorderWhereUniqueInput } from "../../po3aorder/base/Po3aorderWhereUniqueInput";
import { ApiProperty } from "@nestjs/swagger";

@InputType()
class Po3aorderCreateNestedManyWithoutOfStoresInput {
  @Field(() => [Po3aorderWhereUniqueInput], {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: () => [Po3aorderWhereUniqueInput],
  })
  connect?: Array<Po3aorderWhereUniqueInput>;
}

export { Po3aorderCreateNestedManyWithoutOfStoresInput as Po3aorderCreateNestedManyWithoutOfStoresInput };
